filter_names = [['Item Category',
'Item Rarity'],
['Damage',
'Attacks per Second',
'Critical Chance',
'Damage per Second',
'Physical DPS',
'Elemental DPS'],
['Armour',
'Evasion',
'Energy Shield',
'Ward',
'Block',
'Base Percentile'],
['Sockets',
'Links'],
['Level',
'Strength',
'Dexterity',
'Intelligence',
'Character Class'],
['Map Tier',
'Map Packsize',
'Map IIQ',
'Map IIR',
'Area Level',
'Blighted Map',
'Blight-ravaged Map',
'Map Series'],
['Wings Revealed',
'Total Wings',
'Escape Routes Revealed',
'Total Escape Routes',
'Reward Rooms Revealed',
'Total Reward Rooms',
'Contract Objective Value',
'Lockpicking Level',
'Brute Force Level',
'Perception Level',
'Demolition Level',
'Counter-Thaum. Level',
'Trap Disarmament Level',
'Agility Level',
'Deception Level',
'Engineering Level'],
['Duration',
'Enemies Empowered',
'Empowerment',
'Durability',
'Max Durability'],
['Quality',
'Item Level',
'Gem Level',
'Gem Experience %',
'Gem Quality Type',
'Fractured Item',
'Synthesised Item',
'Searing Exarch Item',
'Eater of Worlds Item',
'Alternate Art',
'Identified',
'Corrupted',
'Mirrored',
'Split',
'Crafted']]